version: '3.1'

services:

  db:
    image: postgres:14.3-alpine
    restart: always
    environment:
      POSTGRES_DB: mizudo
      POSTGRES_USER: mizudo
      POSTGRES_PASSWORD: teste123
    volumes:
      - ".data/:/var/lib/postgresql/data"
    ports:
      - "15432:5432"