@startuml
actor Usuario as us
actor "Usuario 2" as us2
actor "Usuario 3" as us3

usecase "Adicionar Perfil" as ai
usecase "Editar Perfil" as ae

us --> ai
us2 --> ae 

us2 <|-- us

us <|-- us3

@enduml